name: Deploy Cognite Function
on:
  push:
jobs:
  deploy:
    name: Deploy
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cognite-sdk-experimental
      - name: Test code
        run: echo "AlL tEStS PaSsED"
      - name: Deploy
        uses: ./
        with:
          cdf_project: andershaf
          cdf_credentials: ${{ secrets.COGNITE_API_KEY }}
      - name: Run integration tests
        run: echo "AlL tEStS PaSsED"
